---
name: Check dotfiles
on:
  schedule:
    - cron:  '30 23 */3 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check dots version
      run: |
        SHA=$(curl https://api.github.com/repos/txgvnn/dots/commits/master | jq -r '.sha')
        TAG="v$(date +%Y%m%d)"
        sed -i 's,DOTS_VERSION=.*,DOTS_VERSION='"$SHA"',' Dockerfile
        git add -u
        git commit -m "$TAG release"
        if [ $? -eq 0 ]; then
          git push origin main
          git tag "$TAG"
          git push origin "$TAG"
        fi
